Introduction
	Relationship to Other Documents
		System Interfaces
			Process Attributes
			Concurrent Execution of Processes
			File Access Permissions
			File Read, Write, and Creation
			File Removal
			File Time Values
			File Contents
			Pathname Resolution
			Changing the Current Working Directory
			Establish the Locale
			Actions Equivalent to Functions
		Concepts Derived from the ISO C Standard
			Arithmetic Precision and Operations
			Mathematical Functions
	Utility Limits
	Grammar Conventions
	Utility Description Defaults
	Considerations for Utilities in Support of Files of Arbitrary Size
	Built-In Utilities
Shell Command Language
	Shell Introduction
	Quoting
		Escape Character (Backslash)
		Single-Quotes
		Double-Quotes
	Token Recognition
		Alias Substitution
	Reserved Words
	Parameters and Variables
		Positional Parameters
		Special Parameters
		Shell Variables
	Word Expansions
		Tilde Expansion
		Parameter Expansion
			Examples
		Command Substitution
		Arithmetic Expansion
			Examples
		Field Splitting
		Pathname Expansion
		Quote Removal
	Redirection
		Redirecting Input
		Redirecting Output
		Appending Redirected Output
		Here-Document
			Examples
		Duplicating an Input File Descriptor
		Duplicating an Output File Descriptor
		Open File Descriptors for Reading and Writing
	Exit Status and Errors
		Consequences of Shell Errors
		Exit Status for Commands
	Shell Commands
		Simple Commands
			Command Search and Execution
		Pipelines
			Exit Status
		Lists
			Examples
			Asynchronous Lists
			Exit Status
			Sequential Lists
			Exit Status
			AND Lists
			Exit Status
			OR Lists
			Exit Status
		Compound Commands
			Grouping Commands
			Exit Status
			The for Loop
			Exit Status
			Case Conditional Construct
			Exit Status
			The if Conditional Construct
			Exit Status
			The while Loop
			Exit Status
			The until Loop
			Exit Status
		Function Definition Command
			Exit Status
	Shell Grammar
		Shell Grammar Lexical Conventions
		Shell Grammar Rules
	Signals and Error Handling
	Shell Execution Environment
	Pattern Matching Notation
		Patterns Matching a Single Character
		Patterns Matching Multiple Characters
		Patterns Used for Filename Expansion
	Special Built-In Utilities
	break
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	colon
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	continue
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	dot
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	eval
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	exec
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	exit
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	export
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	readonly
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	return
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	set
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	shift
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	times
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	trap
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	unset
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
Batch Environment Services
	General Concepts
		Batch Client-Server Interaction
		Batch Queues
		Batch Job Creation
		Batch Job Tracking
		Batch Job Routing
		Batch Job Execution
		Batch Job Exit
		Batch Job Abort
		Batch Authorization
		Batch Administration
		Batch Notification
	Batch Services
		Batch Job States
		Deferred Batch Services
			Batch Job Execution
			Legend
			Legend
			Account_Name Attribute
			Checkpoint Attribute
			Error_Path Attribute
			Execution_Time Attribute
			Hold_Types Attribute
			Job_Owner Attribute
			Join_Path Attribute
			Keep_Files Attribute
			Mail_Points and Mail_Users Attributes
			Output_Path Attribute
			Priority Attribute
			Rerunable Attribute
			Resource_List Attribute
			Shell_Path_List Attribute
			User_List Attribute
			Variable_List Attribute
			Batch Job Routing
			Batch Job Exit
			Batch Server Restart
			Batch Job Abort
		Requested Batch Services
			Delete Batch Job Request
			Hold Batch Job Request
			Batch Job Message Request
			Batch Job Status Request
			Locate Batch Job Request
			Modify Batch Job Request
			Move Batch Job Request
			Queue Batch Job Request
			Batch Queue Status Request
			Release Batch Job Request
			Rerun Batch Job Request
			Select Batch Jobs Request
			Server Shutdown Request
			Server Status Request
			Signal Batch Job Request
			Track Batch Job Request
	Common Behavior for Batch Environment Utilities
		Batch Job Identifier
		Destination
		Multiple Keyword-Value Pairs
Utilities
	admin
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	alias
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	ar
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	asa
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	at
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	awk
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Overall Program Structure
			Expressions in awk
			Variables and Special Variables
			Regular Expressions
			Patterns
			Special Patterns
			Expression Patterns
			Pattern Ranges
			Actions
			Output Statements
			Functions
			Arithmetic Functions
			String Functions
			Input/Output and General Functions
			User-Defined Functions
			Grammar
			Lexical Conventions
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	basename
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	batch
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	bc
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Grammar
			Lexical Conventions in bc
			Operations in bc
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	bg
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	c99
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Standard Libraries
			External Symbols
			Header Search
			Programming Environments
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	cal
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	cat
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	cd
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	cflow
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	chgrp
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	chmod
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Grammar for chmod
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	chown
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	cksum
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	cmp
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	comm
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	command
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	compress
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	cp
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	crontab
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	csplit
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	ctags
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	cut
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	cxref
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	date
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
			Conversion Specifications
			Modified Conversion Specifications
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
	dd
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	delta
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			System Date and Time
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	df
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	diff
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
			Diff Directory Comparison Format
			Diff Binary Output Format
			Diff Default Output Format
			Diff -e Output Format
			Diff -f Output Format
			Diff -c or -C Output Format
			Diff -u or -U Output Format
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	dirname
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	du
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	echo
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	ed
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Regular Expressions in ed
			Addresses in ed
			Commands in ed
			Append Command
			Change Command
			Delete Command
			Edit Command
			Edit Without Checking Command
			Filename Command
			Global Command
			Interactive Global Command
			Help Command
			Help-Mode Command
			Insert Command
			Join Command
			Mark Command
			List Command
			Move Command
			Number Command
			Print Command
			Prompt Command
			Quit Command
			Quit Without Checking Command
			Read Command
			Substitute Command
			Copy Command
			Undo Command
			Global Non-Matched Command
			Interactive Global Not-Matched Command
			Write Command
			Line Number Command
			Shell Escape Command
			Null Command
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	env
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	ex
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Initialization in ex and vi
			Addressing in ex
			Command Line Parsing in ex
			Input Editing in ex
			Scroll
			<newline>
			<backslash>
			<control>-V
			<control>-W
			Command Descriptions in ex
			Abbreviate
			Append
			Arguments
			Change
			Change Directory
			Copy
			Delete
			Edit
			File
			Global
			Insert
			Join
			List
			Map
			Mark
			Move
			Next
			Number
			Open
			Preserve
			Print
			Put
			Quit
			Read
			Recover
			Rewind
			Set
			Shell
			Source
			Substitute
			Suspend
			Tag
			Unabbreviate
			Undo
			Unmap
			Version
			Visual
			Write
			Write and Exit
			Yank
			Adjust Window
			Escape
			Shift Left
			Shift Right
			<control>-D
			Write Line Number
			Execute
			Regular Expressions in ex
			Replacement Strings in ex
			Edit Options in ex
			autoindent, ai
			autoprint, ap
			autowrite, aw
			beautify, bf
			directory, dir
			edcompatible, ed
			errorbells, eb
			exrc
			ignorecase, ic
			list
			magic
			mesg
			number, nu
			paragraphs, para
			prompt
			readonly
			redraw
			remap
			report
			scroll, scr
			sections
			shell, sh
			shiftwidth, sw
			showmatch, sm
			showmode
			slowopen
			tabstop, ts
			taglength, tl
			tags
			term
			terse
			warn
			window
			wrapmargin, wm
			wrapscan, ws
			writeany, wa
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
			Options
			Standard Input
			Input Files
			Asynchronous Events
			Standard Error
			Initialization in ex and vi
			Addressing
			Command Line Parsing in ex
			Input Editing in ex
			eof
			Command Descriptions in ex
			Abbreviate
			Append
			Change
			Change Directory
			Copy
			Delete
			Edit
			File
			Global
			Insert
			Join
			List
			Map
			Mark
			Next
			Open
			Preserve
			Print
			Put
			Read
			Recover
			Rewind
			Substitute
			Set
			Tag
			Undo
			Version
			Write
			Adjust Window
			Escape
			Shift Left and Shift Right
			<control>-D
			Write Line Number
			Execute
			Regular Expressions in ex
			Edit Options in ex
			autoindent, ai
			autoprint, ap
			autowrite, aw
			ignorecase, ic
			paragraphs, para
			readonly
			report
			showmatch, sm
			showmode
			slowopen
			tags
			term
			terse
			window
			wrapmargin, wm
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	expand
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	expr
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Matching Expression
			String Operand
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	false
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	fc
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	fg
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	file
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	find
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	fold
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	fort77
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Standard Libraries
			External Symbols
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	fuser
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	gencat
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	get
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			System Date and Time
			Identification Keywords
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	getconf
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	getopts
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	grep
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	hash
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	head
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	iconv
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	id
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	ipcrm
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	ipcs
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	jobs
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	join
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	kill
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	lex
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Definitions in lex
			Rules in lex
			User Subroutines in lex
			Regular Expressions in lex
			Actions in lex
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	link
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	ln
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	locale
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	localedef
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	logger
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	logname
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	lp
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	ls
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	m4
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	mailx
		NAME
		SYNOPSIS
			Send Mode
			Receive Mode
		DESCRIPTION
			Send Mode
			Receive Mode
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Start-Up in mailx
			Internal Variables in mailx
			Commands in mailx
			Declare Aliases
			Declare Alternatives
			Change Current Directory
			Copy Messages
			Delete Messages
			Discard Header Fields
			Delete Messages and Display
			Echo a String
			Edit Messages
			Exit
			Change Folder
			Display List of Folders
			Follow Up Specified Messages
			Display Header Summary for Specified Messages
			Display Header Summary
			Help
			Hold Messages
			Execute Commands Conditionally
			List Available Commands
			Mail a Message
			Direct Messages to mbox
			Process Next Specified Message
			Pipe Message
			Display Message with Headers
			Display Message
			Quit
			Reply to a Message List
			Reply to a Message
			Retain Header Fields
			Save Messages
			Set Variables
			Invoke a Shell
			Display Message Size
			Read mailx Commands From a File
			Display Beginning of Messages
			Touch Messages
			Delete Aliases
			Undelete Messages
			Unset Variables
			Edit Message with Full-Screen Editor
			Write Messages to a File
			Scroll Header Display
			Invoke Shell Command
			Null Command
			Display Current Message Number
			Command Escapes in mailx
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	make
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Makefile Syntax
			Include Lines
			Makefile Execution
			Target Rules
			Macros
			Inference Rules
			Libraries
			Internal Macros
			Default Rules
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	man
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 7
	mesg
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	mkdir
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 7
	mkfifo
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	more
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Help
			Scroll Forward One Screenful
			Scroll Backward One Screenful
			Scroll Forward One Line
			Scroll Backward One Line
			Scroll Forward One Half Screenful
			Skip Forward One Line
			Scroll Backward One Half Screenful
			Go to Beginning of File
			Go to End-of-File
			Refresh the Screen
			Discard and Refresh
			Mark Position
			Return to Mark
			Return to Previous Position
			Search Forward for Pattern
			Search Backward for Pattern
			Repeat Search
			Repeat Search in Reverse
			Examine New File
			Examine Next File
			Examine Previous File
			Go to Tag
			Invoke Editor
			Display Position
			Quit
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	mv
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	newgrp
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	nice
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	nl
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	nm
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	nohup
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	od
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	paste
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	patch
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Patch File Format
			Filename Determination
			Patch Application
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	pathchk
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	pax
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
			List Mode Format Specifications
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			pax Interchange Format
			pax Header Block
			pax Extended Header
			pax Extended Header Keyword Precedence
			pax Extended Header File Times
			ustar Interchange Format
			cpio Interchange Format
			cpio Header
			cpio Filename
			cpio File Data
			cpio Special Entries
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
			pax Interchange Format
			pax Archive Character Set Encoding/Decoding
			ustar Interchange Format
			cpio Interchange Format
			cpio Header
			cpio Filename
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	pr
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	printf
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	prs
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
			Data Keywords
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	ps
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	pwd
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qalter
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qdel
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qhold
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qmove
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qmsg
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qrerun
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qrls
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qselect
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	qsig
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qstat
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	qsub
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Script Preservation
			Option Specification
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	read
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	renice
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	rm
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	rmdel
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	rmdir
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	sact
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	sccs
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	sed
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Addresses in sed
			Regular Expressions in sed
			Editing Commands in sed
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	sh
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Command History List
			Command Line Editing
			Command Line Editing (vi-mode)
			vi Line Editing Insert Mode
			vi Line Editing Command Mode
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	sleep
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	sort
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	split
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	strings
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	strip
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	stty
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
			Control Modes
			Input Modes
			Output Modes
			Local Modes
			Special Control Character Assignments
			Combination Modes
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	tabs
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	tail
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	talk
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	tee
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	test
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	time
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	touch
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	tput
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	tr
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	true
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
	tsort
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	tty
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
	type
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	ulimit
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	umask
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	unalias
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	uname
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	uncompress
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	unexpand
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	unget
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	uniq
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	unlink
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	uucp
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	uudecode
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	uuencode
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
			uuencode Base64 Algorithm
			uuencode Historical Algorithm
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	uustat
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	uux
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	val
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	vi
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
			Initialization in ex and vi
			Command Descriptions in vi
			Page Backwards
			Scroll Forward
			Scroll Forward by Line
			Page Forward
			Display Information
			Move Cursor Backwards
			Move Down
			Clear and Redisplay
			Move Up
			Redraw Screen
			Scroll Backward
			Scroll Backward by Line
			Edit the Alternate File
			Terminate Command or Input Mode
			Search for tagstring
			Move Cursor Forward
			Replace Text with Results from Shell Command
			Move Cursor to End-of-Line
			Move to Matching Character
			Repeat Substitution
			Return to Previous Context at Beginning of Line
			Return to Previous Context
			Return to Previous Section
			Move to Next Section
			Move to First Non-<blank> Position on Current Line
			Current and Line Above
			Move Back to Beginning of Sentence
			Move Forward to Beginning of Sentence
			Move Back to Preceding Paragraph
			Move Forward to Next Paragraph
			Move to Specific Column Position
			Reverse Find Character
			Repeat
			Find Regular Expression
			Move to First Character in Line
			Execute an ex Command
			Repeat Find
			Shift Left
			Shift Right
			Scan Backwards for Regular Expression
			Execute
			Reverse Case
			Append
			Append at End-of-Line
			Move Backward to Preceding Word
			Move Backward to Preceding Bigword
			Change
			Change to End-of-Line
			Delete
			Delete to End-of-Line
			Move to End-of-Word
			Move to End-of-Bigword
			Find Character in Current Line (Forward)
			Find Character in Current Line (Reverse)
			Move to Line
			Move to Top of Screen
			Insert Before Cursor
			Insert at Beginning of Line
			Join
			Move to Bottom of Screen
			Mark Position
			Move to Middle of Screen
			Repeat Regular Expression Find (Forward)
			Repeat Regular Expression Find (Reverse)
			Insert Empty Line Below
			Insert Empty Line Above
			Put from Buffer Following
			Put from Buffer Before
			Enter ex Mode
			Replace Character
			Replace Characters
			Substitute Character
			Substitute Lines
			Move Cursor to Before Character (Forward)
			Move Cursor to After Character (Reverse)
			Undo
			Undo Current Line
			Move to Beginning of Word
			Move to Beginning of Bigword
			Delete Character at Cursor
			Delete Character Before Cursor
			Yank
			Yank Current Line
			Redraw Window
			Exit
			Input Mode Commands in vi
			NUL
			<control>-D
			<control>-H
			<newline>
			<control>-T
			<control>-U
			<control>-V
			<control>-W
			<ESC>
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
			Initialization in ex and vi
			Command Descriptions in vi
			Page Backwards
			Scroll Forward
			Scroll Forward by Line
			Clear and Redisplay
			Redraw Screen
			Search for tagstring
			Replace Text with Results from Shell Command
			Move to Matching Character
			Repeat Substitution
			Return to Previous (Context or Section)
			Repeat
			Find Regular Expression
			Execute an ex Command
			Shift Left (Right)
			Execute
			Reverse Case
			Append
			Move Backward to Preceding Word
			Change to End-of-Line
			Delete
			Delete to End-of-Line
			Join
			Mark Position
			Repeat Regular Expression Find (Forward and Reverse)
			Insert Empty Line (Below and Above)
			Put from Buffer (Following and Before)
			Replace Character
			Replace Characters
			Undo
			Yank
			Yank Current Line
			Redraw Window
			Input Mode Commands in vi
			NUL
			<control>-D
			<newline>
			<control>-T
			<control>-V
			<ESC>
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	wait
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	wc
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 7
	what
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
	who
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 6
		Issue 7
	write
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	xargs
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	yacc
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
			Code File
			Header File
			Description File
		EXTENDED DESCRIPTION
			Input Language
			Lexical Structure of the Grammar
			Declarations Section
			Grammar Rules in yacc
			Programs Section
			Input Grammar
			Conflicts
			Error Handling
			Interface to the Lexical Analyzer
			Completing the Program
			Yacc Library
			Debugging the Parser
			Algorithms
			Limits
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
		Issue 5
		Issue 6
		Issue 7
	zcat
		NAME
		SYNOPSIS
		DESCRIPTION
		OPTIONS
		OPERANDS
		STDIN
		INPUT FILES
		ENVIRONMENT VARIABLES
		ASYNCHRONOUS EVENTS
		STDOUT
		STDERR
		OUTPUT FILES
		EXTENDED DESCRIPTION
		EXIT STATUS
		CONSEQUENCES OF ERRORS
		APPLICATION USAGE
		EXAMPLES
		RATIONALE
		FUTURE DIRECTIONS
		SEE ALSO
		CHANGE HISTORY
.